### ISSUE TITLE
Does this use Spotify's Basic Pitch algorithm?

### ISSUE THREAD

**Issue by godofecht** [rnheroes/react-native-pitchy#6]
Does this use Spotify's Basic Pitch algorithm?

If not, have you ever compared the performance?

**Comment by yigithanyucedag** [comment]
No, I don’t use Spotify’s Basic Pitch algorithm—I use the autocorrelation method instead. Basic Pitch is a deep learning-based approach designed for polyphonic music transcription, while autocorrelation is a more traditional signal processing method, typically used for pitch detection in monophonic sounds. I haven’t directly compared the two, as I’ve mainly focused on testing how well the autocorrelation method performs across both platforms.

**Comment by yigithanyucedag** [comment]
If you’re interested in implementing and comparing different methods, feel free to give it a shot and open a pull request. I’d love to see it!
